Update repair_ro
*Changed the detection method to use blkid instead of using /proc/cmdline so it can be used on x86 devices.
*Adding argumen as alternate user input for rootfs device, eg. repair_ro /dev/sda2.

diff --git a/usr/bin/repair_ro b/usr/bin/repair_ro
--- a/usr/bin/repair_ro
+++ b/usr/bin/repair_ro
@@ -2,16 +2,23 @@
 # Created by Frizkyiman
 # Github https://github.com/frizkyiman/
 
-# Finding root partition and status
-root_device=$(cat /proc/cmdline | grep -o 'root=[^ ]*' | sed 's/root=//')
-ro_status=$(mount | awk '/\/dev\/root/ && /ro,/ {print $6}' | grep -o 'ro' | head -n 1)
+if [ -n "$1" ]; then
+    root_device="$1"
+    if ! blkid | grep -q "$root_device:"; then
+        echo "Root file system device not found in the system. Unable to repair."
+        exit 1
+    fi
+else
+    root_device=$(blkid -L rootfs -o device)
+fi
 
 if [ -z "$root_device" ]; then
-    echo "Root file system not found. Unable to repair."
+    echo "Root file system device not found in the system. Unable to repair."
     exit 1
 fi
 
-# Checking root partition status and repairing if needed
+ro_status=$(mount | awk '/\/dev\/root/ && /ro,/ {print $6}' | grep -o 'ro' | head -n 1)
+
 if [ "$ro_status" = "ro" ]; then
     echo "Detected root file system: $root_device"
     echo "The file system is currently read-only. Initiating repair..."
@@ -21,11 +28,11 @@ if [ "$ro_status" = "ro" ]; then
         echo "Mounting $root_device to read-write"
         mount -o remount,rw "$root_device" /
         echo "Rebooting the system..."
-        reboot
+        sudo reboot
     else
         echo "An error occurred while repairing the file system."
     fi
  
 else
-    echo "The root file system $root_device is currently in read-write mode."
+    echo "The rootfs $root_device is currently in read-write mode."
 fi
